### ISSUE TITLE
Music Feature - Error 127

### ISSUE THREAD

**Issue by Permanently** [TheSharks/WildBeast#241]
I'm trying to request a song on WildBeast, but everytime I get this error:
> error:  killed=false, code=127, signal=null, cmd=/root/WildBeast/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best --skip-download -f bestaudio/worstvideo --add-header Authorization:hidden-api-key http://www.youtube.com/watch?v=riezARcGZtk, done=true

I've tried `npm install` and `npm rebuild youtube-dl` but that's not worked. Anything else that could be causing this issue?

**Comment by SteamingMutt** [comment]
Error 127 indicates youtube-dl is incorrectly installed, usually a rebuild should fix this.

**Comment by Permanently** [comment]
I've rebuilt it (for the second time), still getting the same error. :/

**Comment by Permanently** [comment]
Why was this closed- was the bug fixed? 🤔

**Comment by LWTechGaming** [comment]
It's not a bug, but a problem with your local installation. You could try removing the `node_modules` folder and redo `npm install`. Code 127 means that youtube-dl cannot be found or is incorrectly installed which isn't dependent on us in any manner.

**Comment by Permanently** [comment]
Ah right, sorry. My bad. :P

**Comment by Permanently** [comment]
Okay, I've found the solution- you have to use apt-get to install youtube-dl for Ubuntu.
`sudo apt-get install youtube-dl`
I suggest adding that to the docs so that people don't get confused :)

**Comment by LWTechGaming** [comment]
The method doesn't really matter. You're using a different package manager which essentially leads to it being installed in a different directory. NPM installs it in the local node_modules folder while Aptitude installs it to a different place, /etc/something depending on what Linux distro you use.

The documentation instructions for running the bot have been tested and proven fully functional. There should be no issue with installing it through NPM and circumventing it with Aptitude is very rough. You may use that if you prefer but it's not something we consider good enough to add to the docs.
